import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbH2SSE4lGjW5OvsNlGxyYM4v8sVuuh3k',
    appId: '1:750939063581:web:a2c63d1351036c41f60df4',
    messagingSenderId: '750939063581',
    projectId: 'student-registration-aa838',
    authDomain: 'student-registration-aa838.firebaseapp.com',
    storageBucket: 'student-registration-aa838.firebasestorage.app',
    measurementId: 'G-B7NNJSL6RP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Jo4IKejHF4OkDTk8LzVxD0BrgS6yv0Y',
    appId: '1:750939063581:android:3d15b38c3eeffe15f60df4',
    messagingSenderId: '750939063581',
    projectId: 'student-registration-aa838',
    storageBucket: 'student-registration-aa838.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaVjMAIPwmewnFPTAek-RFs1nWWFkmPM4',
    appId: '1:750939063581:ios:aeb46ee1f1c33ba3f60df4',
    messagingSenderId: '750939063581',
    projectId: 'student-registration-aa838',
    storageBucket: 'student-registration-aa838.firebasestorage.app',
    iosBundleId: 'com.example.studentRegisteration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaVjMAIPwmewnFPTAek-RFs1nWWFkmPM4',
    appId: '1:750939063581:ios:aeb46ee1f1c33ba3f60df4',
    messagingSenderId: '750939063581',
    projectId: 'student-registration-aa838',
    storageBucket: 'student-registration-aa838.firebasestorage.app',
    iosBundleId: 'com.example.studentRegisteration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbH2SSE4lGjW5OvsNlGxyYM4v8sVuuh3k',
    appId: '1:750939063581:web:2f27096fdc748c25f60df4',
    messagingSenderId: '750939063581',
    projectId: 'student-registration-aa838',
    authDomain: 'student-registration-aa838.firebaseapp.com',
    storageBucket: 'student-registration-aa838.firebasestorage.app',
    measurementId: 'G-Z9DG3PNFS4',
  );
}
